FROM python:3.13-slim

WORKDIR /src

RUN apt-get update && apt-get install -y \
    cron \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip3 install torch torchvision

COPY src/ .

COPY docker/crontab /etc/cron.d/jobs-cron
RUN chmod 0644 /etc/cron.d/jobs-cron

CMD ["cron", "-f"]