FROM pytorch/pytorch:2.11.0-cuda13.0-cudnn9-devel

RUN apt-get update && apt-get install -y cron && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY requirements.txt .

RUN pip install --break-system-packages -r requirements.txt

COPY src/ .

RUN touch /var/log/cron.log

RUN echo "0 2 * * * root cd /src && /usr/local/bin/ipython3 jobs.py" > /etc/cron.d/jobs
RUN chmod 0644 /etc/cron.d/jobs

CMD ["cron", "-f"]
